# Generated by Django 3.2 on 2023-04-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_genre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'ordering': ('id',), 'verbose_name': 'Соответствие жанра и произведения'},
        ),
    ]
